[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
  "https://prefix.dev/robostack-jazzy",
]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
preview = ["pixi-build"]

[package.build.backend]
name    = "pixi-build-ros"
version = ">=0.1.3"

[package.build.config]
distro = "jazzy"
